[package]
name = "minibin"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3.9", features = ["shellapi", "winerror", "winuser"] }
wio = "0.2.2"
tray-icon = "0.20.1"
winit = "0.30"
image = "0.25"
winreg = "0.55.0"

[build-dependencies]
embed-resource = "3"
